################################################################################
# Environment script generated by ilcsoft-install on Thu Jun 12 07:46:35 2014
# for Mokka located at [ /besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/Mokka/mokka-08-03 ]
################################################################################


#--------------------------------------------------------------------------------
#     Global Environment Variables
#--------------------------------------------------------------------------------
export MAKEOPTS="-j8"
export CXX="g++"
export ILCSOFT_CMAKE="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/ILCSoft.cmake"
export CC="gcc"
export FC="gfortran"
export ILCSOFT_CMAKE_ENV="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/ILCSoft.cmake.env.sh"


#--------------------------------------------------------------------------------
#     Mokka
#--------------------------------------------------------------------------------
export MOKKA="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/Mokka/mokka-08-03"
export PATH="$MOKKA/bin:$PATH"


#--------------------------------------------------------------------------------
#     LCIO
#--------------------------------------------------------------------------------
export LCIO="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/lcio/v02-04-03"
export PATH="$LCIO/tools:$LCIO/bin:$PATH"
export LD_LIBRARY_PATH="$LCIO/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CLHEP
#--------------------------------------------------------------------------------
export CLHEP="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/CLHEP/2.1.3.1"
export CLHEP_BASE_DIR="$CLHEP"
export CLHEP_INCLUDE_DIR="$CLHEP/include"
export PATH="$CLHEP_BASE_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$CLHEP_BASE_DIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     ROOT
#--------------------------------------------------------------------------------
export ROOTSYS="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/root/5.34.07"
export PATH="$ROOTSYS/bin:$PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GEAR
#--------------------------------------------------------------------------------
export GEAR="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/gear/v01-04"
export PATH="$GEAR/tools:$GEAR/bin:$PATH"
export LD_LIBRARY_PATH="$GEAR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     Geant4
#--------------------------------------------------------------------------------
export G4INSTALL="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/geant4/9.6.p02"
export G4ENV_INIT="$G4INSTALL/bin/geant4.sh"
export G4SYSTEM="Linux-g++"


#--------------------------------------------------------------------------------
#     QT
#--------------------------------------------------------------------------------
export QTDIR="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/QT/4.7.4"
export QMAKESPEC="$QTDIR/mkspecs/linux-g++"
export PATH="$QTDIR/bin:$PATH"
export LD_LIBRARY_PATH="$QTDIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     MySQL
#--------------------------------------------------------------------------------
export MYSQL_HOME="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/mysql/usr"
export MYSQL_LIBDIR="$MYSQL_HOME/lib64/mysql"
export MYSQL_PATH="$MYSQL_HOME"
export MYSQL="$MYSQL_HOME"
export PATH="$MYSQL_HOME/bin:$PATH"
export LD_LIBRARY_PATH="$MYSQL_HOME/lib64/mysql:$MYSQL_HOME/lib64:$MYSQL_HOME/lib/mysql:$MYSQL_HOME/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CMake
#--------------------------------------------------------------------------------
export PATH="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/CMake/2.8.5/bin:$PATH"


#--------------------------------------------------------------------------------
#     ILCUTIL
#--------------------------------------------------------------------------------
export ilcutil="/besfs/groups/higgs/data/workarea_xy/soft/v01-17-05/ilcutil/v01-01"
export LD_LIBRARY_PATH="$ilcutil/lib:$LD_LIBRARY_PATH"
# --- additional comands ------- 
export G4WORKDIR=$MOKKA
test -r ${G4ENV_INIT} && { cd $(dirname ${G4ENV_INIT}) ; . ./$(basename ${G4ENV_INIT}) ; cd $OLDPWD ; }
